const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Behaviors.Car,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Car.Acts.SimulateControl,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Car.Exps.Speed,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Car.Acts.SetEnabled,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Physics: 0},
	{Wall: 0},
	{Wall2: 0},
	{Car: 0},
	{Car01: 0},
	{Keyboard: 0},
	{Car02: 0},
	{Ball: 0},
	{GolsP1: 0},
	{GolsP2: 0},
	{Gol1Collison: 0},
	{Gol2Collison: 0},
	{Gooool: 0},
	{TextTime: 0},
	{TextTimeOut: 0},
	{TextP1Wins: 0},
	{TextP2Wins: 0},
	{TextNoWinner: 0},
	{GolsPlayer1: 0},
	{GameTime: 0},
	{GolsPlayer2: 0},
	{Winner: 0}
];

self.InstanceType = {
	Wall: class extends self.ISpriteInstance {},
	Wall2: class extends self.ISpriteInstance {},
	Car01: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Car02: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	GolsP1: class extends self.ITextInstance {},
	GolsP2: class extends self.ITextInstance {},
	Gol1Collison: class extends self.ISpriteInstance {},
	Gol2Collison: class extends self.ISpriteInstance {},
	Gooool: class extends self.ITextInstance {},
	TextTime: class extends self.ITextInstance {},
	TextTimeOut: class extends self.ITextInstance {},
	TextP1Wins: class extends self.ITextInstance {},
	TextP2Wins: class extends self.ITextInstance {},
	TextNoWinner: class extends self.ITextInstance {}
}